[project]
name = "image-rename"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yonglin", email = "yonglintan@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.3.0",
    "typer>=0.27.1",
]

[project.scripts]
image-rename = "image_rename.cli:app"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "commitizen>=4.18.0",
    "pyinstaller>=6.22.2",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
