# Uses PyInstaller to build and release the windows executable for the CLI tool.

name: Release Windows Executable

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Install project dependencies
        run: uv sync --locked --no-dev

      - name: Build executable with PyInstaller
        run: uv run --with pyinstaller pyinstaller image-rename.spec

      - name: Create GitHub Release and Upload Binary
        uses: softprops/action-gh-release@v3
        with:
          files: dist/image-rename/
